#!/bin/sh

URL="http://admin@localhost/rest/apps"
PKG="50_@Bundle-SymbolicName@.jar 50_NativeSerialTransport.jar 50_com.nordicid.nativeserial-@PLATFORM@.jar 50_NurApi.jar"

for pkg in $PKG; do
  busybox wget $URL/$pkg/unplug -q --spider
done

exit 0
